kind: Project
apiVersion: garden.io/v2
name: sward-warden

variables:
  pr-number: ${local.env.PR_NUMBER || "local"}
  kube-context: "${local.env.GARDEN_KUBECONTEXT || (local.env.CI == 'true' ? 'local' : 'kubernetes-admin@kubernetes')}"
  current-namespace: ${environment.defaultNamespace || "default"}

providers:
  - name: kubernetes
    context: ${var.kube-context}
    namespace: ${environment.namespace}
    environments:
      - pr
      - local

environments:
  - name: local
    defaultNamespace: sward-warden-${local.env.USER}
  - name: pr
    defaultNamespace: sward-warden-pr-${var.pr-number}

---
kind: Deploy
type: helm
name: sward-warden
description: "Deploy the sward manager"
source:
  path: charts/sward-warden
include:
  - charts/sward-warden/**/*
spec:
  values:
    fe:
      image:
        repository: ${local.env.SW_FE_IMAGE || "sward-warden-fe"}
        tag: ${local.env.SW_FE_TAG || "latest"}
    be:
      image:
        repository: ${local.env.SW_BE_IMAGE || "sward-warden-be"}
        tag: ${local.env.SW_BE_TAG || "latest"}
