{{- if .Values.be.devsecops.AuthorizationPolicy.rules }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    {{- include "sward-warden.be.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sward-warden.be.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  {{-  tpl (toYaml .Values.be.devsecops.AuthorizationPolicy.rules) . | nindent 4 }}
{{- end }}
