apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    app.kubernetes.io/name: be
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    {{- include "sward-warden.be.config" . | nindent 4 }}
