{{- $configsha := tpl (include "sward-warden.be.config" .) . | sha256sum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    {{- include "sward-warden.be.labels" . | nindent 4 }}
spec:
  {{- if not .Values.be.autoscaling.enabled }}
  replicas: {{ .Values.be.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sward-warden.be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configsha }}
      {{- with .Values.be.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sward-warden.be.selectorLabels" . | nindent 8 }}
      {{- with .Values.be.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "sward-warden.be.serviceAccountName" . }}
      {{- with .Values.be.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.be.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.be.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.be.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: migrate
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          imagePullPolicy: {{ .Values.be.image.pullPolicy }}
          command: ["/usr/local/bin/sw-be-container", "--config-path", "/etc/sw-be/config.yaml", "--secrets-dir", "/etc/sw-be/secrets", "migrate"]
          {{- with .Values.be.initContainer.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "sward-warden.be.volumeMounts" . | nindent 12 }}
      containers:
        - name: be
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          imagePullPolicy: {{ .Values.be.image.pullPolicy }}
          command: ["/usr/local/bin/sw-be-container", "--config-path", "/etc/sw-be/config.yaml", "--secrets-dir", "/etc/sw-be/secrets", "serve"]
          env:
            {{- include "sward-warden.be.env" . | nindent 12 }}
          ports:
            - name: http-web
              containerPort: {{ .Values.be.containerPort }}
              protocol: TCP
            - name: http-lifecycle
              containerPort: {{ .Values.be.lifecyclePort }}
              protocol: TCP
          lifecycle:
            {{- toYaml .Values.be.lifecycle | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.be.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.be.livenessProbe | nindent 12 }}
          volumeMounts: {{- include "sward-warden.be.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "sward-warden.be.volumes" . | nindent 8 }}
