apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    app.kubernetes.io/name: be
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.be.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: be
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: migrate
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          imagePullPolicy: {{ .Values.be.image.pullPolicy }}
          command: ["/app/sw-be-container", "migrate"]
      containers:
        - name: be
          image: "{{ .Values.be.image.repository }}:{{ .Values.be.image.tag }}"
          imagePullPolicy: {{ .Values.be.image.pullPolicy }}
          command: ["/app/sw-be-container", "serve"]
          ports:
            - name: http
              containerPort: {{ .Values.be.service.appPort }}
              protocol: TCP
            - name: lifecycle
              containerPort: {{ .Values.be.service.lifecyclePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: lifecycle
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: lifecycle
            initialDelaySeconds: 5
            periodSeconds: 10
