{{- $configsha := substr 0 8 ((include "sward-warden.config" . ) | sha256sum) }}
{{- $volumesha := substr 0 8 ((include "sward-warden.volumes" . ) | sha256sum) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    {{- include "sward-warden.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sward-warden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configsha }}
        checksum/volumes: {{ $volumesha }}
        {{- if .Values.customPodSHA }}
        checksum/custom: {{ .Values.customPodSHA | quote }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sward-warden.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "sward-warden.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/sw-be-container", "--config-path", "/etc/sw-be/config.yaml", "--secrets-dir", "/etc/sw-be/secrets", "migrate"]
          {{- with .Values.initContainer.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "sward-warden.volumeMounts" . | nindent 12 }}
      containers:
        - name: be
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/sw-be-container", "--config-path", "/etc/sw-be/config.yaml", "--secrets-dir", "/etc/sw-be/secrets", "serve"]
          env:
            {{- include "sward-warden.env" . | nindent 12 }}
          ports:
            - name: http-web
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            - name: http-lifecycle
              containerPort: {{ .Values.lifecyclePort }}
              protocol: TCP
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "sward-warden.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "sward-warden.volumes" . | nindent 8 }}
