apiVersion: v1
kind: Service
metadata:
  name: {{ include "sward-warden.fullname" . }}-be
  labels:
    app.kubernetes.io/name: be
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.be.service.type }}
  ports:
    - port: {{ .Values.be.service.appPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.be.service.lifecyclePort }}
      targetPort: lifecycle
      protocol: TCP
      name: lifecycle
  selector:
    app.kubernetes.io/name: be
    app.kubernetes.io/instance: {{ .Release.Name }}
