apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sward-warden.fullname" . }}-fe
  labels:
    app.kubernetes.io/name: fe
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.fe.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fe
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fe
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fe
          image: "{{ .Values.fe.image.repository }}:{{ .Values.fe.image.tag }}"
          imagePullPolicy: {{ .Values.fe.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
