apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sward-warden.fullname" . }}-fe
  labels:
    {{- include "sward-warden.fe.labels" . | nindent 4 }}
spec:
  {{- if not .Values.fe.autoscaling.enabled }}
  replicas: {{ .Values.fe.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sward-warden.fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.fe.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sward-warden.fe.selectorLabels" . | nindent 8 }}
      {{- with .Values.fe.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.fe.serviceAccount.create }}
      serviceAccountName: {{ include "sward-warden.fe.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.fe.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fe.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fe.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fe.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fe
          image: "{{ .Values.fe.image.repository }}:{{ .Values.fe.image.tag }}"
          imagePullPolicy: {{ .Values.fe.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
