apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sward-warden.fe.serviceAccountName" . }}
  labels:
    {{- include "sward-warden.fe.labels" . | nindent 4 }}
  {{- with .Values.fe.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
