# Default values for sward-warden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []

fe:
  replicaCount: 1
  image:
    repository: sward-warden-fe
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

be:
  replicaCount: 1
  env: []
  initContainer:
    env: []
  image:
    repository: sward-warden-be
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    appPort: 8080
    lifecyclePort: 8079
