# Default values for sward-warden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []

fe:
  replicaCount: 1
  image:
    repository: sward-warden-fe
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

be:
  replicaCount: 1
  containerPort: 8080
  env: []
  livenessProbe:
    httpGet:
      path: /health
      port: http-lifecycle
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /ready
      port: http-lifecycle
    initialDelaySeconds: 5
    periodSeconds: 10
  lifecycle: {}
    # preStop:
    #   httpGet:
    #     port: http-lifecycle
    #     path: "/hams/stop"
  initContainer:
    env: []
  image:
    repository: sward-warden-be
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  volumeMounts: []
  volumes: []
