---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe-sward-warden
spec:
  releaseName: mfe-sward-warden
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/sward-manager-frontend
      tag: latest
      pullPolicy: Always # Dev ONLY
    env:
      - name: SERVE_ROOT
        value: /mfe/sward-warden
    config:
      contents:
        config.json: |
          {
            "apiUrl": "/sward-be/v0"
          }
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sward-warden
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/sward-warden/helm/sward-manager
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sward-warden
spec:
  releaseName: sward-warden
  chartRef:
    kind: OCIRepository
    name: sward-warden
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    backend:
      image:
        repository: ghcr.io/polecatworks/sward-manager-backend
        tag: latest
        pullPolicy: Always
      configs:
        database:
          url: postgresql://cnpg-db0-cluster-rw.dbs:5432/sward_warden
    volumes:
      - name: secrets
        projected:
          sources:
            - secret:
                name: db0-sward-warden-user
                items:
                  - key: username
                    path: persistence/db/connection/username
                  - key: password
                    path: persistence/db/connection/password
