# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: mfe-sward-warden
# spec:
#   releaseName: mfe-sward-warden
#   chartRef:
#     kind: OCIRepository
#     name: mfe-shell
#     namespace: dev
#   interval: 50m
#   install:
#     remediation:
#       retries: 3
#   values:
#     image:
#       repository: ghcr.io/polecatworks/sward-warden-fe
#       tag: latest
#       pullPolicy: Always # Dev ONLY
#     env:
#       - name: SERVE_ROOT
#         value: /mfe/sward-warden
#     config:
#       contents:
#         config.json: |
#           {
#             "apiUrl": "/sward-be/v0"
#           }
---
# If this is failing with 'DENIED', ensure the PAT in 'sw-gh-pat' has 'read:packages' scope.
# For private GHCR repositories, the username must be the GitHub username.
# Using a 'kubernetes.io/dockerconfigjson' secret is also recommended for OCI.

# kubectl create secret docker-registry ghcr-docker-auth -n sward-warden-dev \
#   --docker-server=ghcr.io \
#   --docker-username=<USERNAME> \
#   --docker-password='<YOUR_WORKING_PAT>'

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sward-warden
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/sward-warden/helm/sward-warden
  secretRef:
    name: ghcr-docker-auth
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main-*
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sward-warden
spec:
  releaseName: sward-warden
  chartRef:
    kind: OCIRepository
    name: sward-warden
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: ghcr-docker-auth
    be:
      initContainer:
        env:
          - name: SP_BE__DEBUGGING__FAIL_DEBUG_DELAY
            value: "60s"
      image:
        repository: ghcr.io/polecatworks/sward-warden-be
        tag: main
        pullPolicy: Always
      config:
        webservice:
          address: http://0.0.0.0:8080/sward
        database:
          url:
            url: postgresql://cnpg-db0-cluster-rw.dbs:5432/sward_warden
            username_file: persistence/db/connection/username
            password_file: persistence/db/connection/password
      volumes:
        - name: config
          configMap:
            name: "{{ include \"sward-warden.fullname\" . }}-be"
        - name: secrets
          projected:
            sources:
              - secret:
                  name: db0-sward-warden-user
                  items:
                    - key: username
                      path: persistence/db/connection/username
                    - key: password
                      path: persistence/db/connection/password
      volumeMounts:
        - name: config
          mountPath: /etc/sw-be/config.yaml
          subPath: config.yaml
        - name: secrets
          mountPath: /etc/sw-be/secrets
    fe:
      image:
        repository: ghcr.io/polecatworks/sward-warden-fe
        tag: main
        pullPolicy: Always
      configs:
        database:
          url:
            url: postgresql://cnpg-db0-cluster-rw.dbs:5432/sward_warden
