---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sward-warden
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/sward-warden/helm/sward-warden
  secretRef:
    name: ghcr-docker-auth
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main-*
# If this is failing with 'DENIED', ensure the PAT in 'sw-gh-pat' has 'read:packages' scope.
# For private GHCR repositories, the username must be the GitHub username.
# Using a 'kubernetes.io/dockerconfigjson' secret is also recommended for OCI.
---

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sward-warden
spec:
  releaseName: sward-warden
  chartRef:
    kind: OCIRepository
    name: sward-warden
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: ghcr-docker-auth
    env:
      - name: RUST_LOG
        value: info
    initContainer:
      env:
        - name: SP_BE__DEBUGGING__FAIL_DEBUG_DELAY
          value: "60s"
    image:
      repository: ghcr.io/polecatworks/sward-warden-be
      tag: sha-f06e862e679b04ccbb996a73ba0ff62ced7974b7
      pullPolicy: Always
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    config:
      webservice:
        address: http://0.0.0.0:8080/sward
        forwarding_headers: []
        cors:
          allow_origins: []
          allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
          allow_headers: ["content-type", "authorization", "x-user-role"]
        timeout: "30s"
        max_connections: 100
      database:
        url:
          url: postgresql://cnpg-db0-cluster-rw.dbs:5432/sward_warden
          username_file: persistence/db/connection/username
          password_file: persistence/db/connection/password
        max_connections: 10
      runtime:
        threads: 0
        stack_size: 3000000
        name: "default"
      debugging:
        fail_debug_delay: 60s
        environment: "development"
        enable_dev_auth: true
        log_level: "info"
    volumes:
      - name: config
        configMap:
          name: '{{ include "sward-warden.fullname" . }}-be'
      - name: secrets
        projected:
          sources:
            - secret:
                name: db0-sward-warden-user
                items:
                  - key: username
                    path: persistence/db/connection/username
                  - key: password
                    path: persistence/db/connection/password
    volumeMounts:
      - name: config
        mountPath: /etc/sw-be/config.yaml
        subPath: config.yaml
      - name: secrets
        mountPath: /etc/sw-be/secrets
    customPodSHA: 08bf410
