---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sward-warden
spec:
  hosts:
    - sward.k8s
  gateways:
    - istio-ingress/k8s-gateway
    - mesh # applies to all the sidecars in the mesh
  http:
    - name: sward-warden-fe
      match:
        - uri:
            prefix: /mfe/sward-warden
      route:
        - destination:
            host: sward-warden-fe
    - name: sward-warden-be
      match:
        - uri:
            prefix: /sward
      route:
        - destination:
            host: sward-warden-be
