---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sward-warden
spec:
  hosts:
    - sward.k8s
  gateways:
    - istio-ingress/k8s-gateway
    - mesh # applies to all the sidecars in the mesh
  http:
    - name: mfe-sward-warden
      match:
        - uri:
            prefix: /mfe/sward-warden
      route:
        - destination:
            host: mfe-sward-warden-nginx-view
    - name: mfe-shell
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: mfe-shell-nginx-view
    - name: sward-warden-be
      match:
        - uri:
            prefix: /sward
      route:
        - destination:
            host: sward-warden-be
