-- Migration 0027: Weather Job Cache & Locking
-- PRD Reference: 0008

CREATE TABLE field_weather_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL,
    precipitation_mm DOUBLE PRECISION NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    is_forecast BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_field_weather_cache_field_id ON field_weather_cache(field_id);
CREATE INDEX idx_field_weather_cache_timestamp ON field_weather_cache(timestamp);

-- Used to store the last time the weather job ran successfully
CREATE TABLE job_locks (
    job_name VARCHAR(255) PRIMARY KEY,
    last_run TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
