name: Cleanup Dev Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set Repository Name
        id: repo
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Cleanup dev backend packages older than 2 weeks
        uses: snok/container-retention-policy@v2.2.1
        with:
          account-type: org
          org-name: ${{ github.repository_owner }}
          image-names: ${{ env.repo_name }}-be%2Fdev
          cut-off: 2 weeks ago UTC
          timestamp-to-use: updated_at
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token

      - name: Cleanup dev frontend packages older than 2 weeks
        uses: snok/container-retention-policy@v2.2.1
        with:
          account-type: org
          org-name: ${{ github.repository_owner }}
          image-names: ${{ env.repo_name }}-fe%2Fdev
          cut-off: 2 weeks ago UTC
          timestamp-to-use: updated_at
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
