name: Cleanup Dev Packages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set Repository Name
        id: repo
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Cleanup dev backend packages older than 2 weeks
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ steps.repo.outputs.repo_name }}-be/dev
          cut-off: 2 weeks ago UTC
          timestamp-to-use: updated_at
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Cleanup dev frontend packages older than 2 weeks
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: ${{ steps.repo.outputs.repo_name }}-fe/dev
          cut-off: 2 weeks ago UTC
          timestamp-to-use: updated_at
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
